### ISSUE TITLE
AXGRID의 "##count(s)" 로 나오는 display 관련 질문입니다.

### ISSUE THREAD

**Issue by bloodiel** [thomasJang/axisj#863]
자꾸 질문 드려서 죄송합니다. ㅠㅠ

다음 예제에 http://dev.axisj.com/samples/AXGrid/inline-edit.html

오른쪽 아랫 부분을 보면 "##count(s)" 로 나오는 그리드 열 수가 나오는데 

저는 AXSearch 로 조건을 주고 DB서 검색된 값을 AXGrid를 통해 보여 주도록 구현했습니다.

문제는 처음 Grid init 단계에서 검색되어 보여지는 그리드 내용의 열 수는 정확히 나오는데

AXSearch 에서 조건을 변경하여 검색 된 결과가 그리드 상에서는 정확히 나오는데

오른쪽 아랫 부분을 보이는 "##count(s)" 로 나오는 그리드 열 수는 변동이 없이 처음 init 단계에서 기본으로 보여지는 정보의 열수 대로만 보여지고 있습니다.

제가 어느 부분에서 놓치고 있는지 확인 해야 될 부분은 어디인지 조언 부탁드립니다.

아예 안되는 것도 아니고 처음엔 됐다가 서칭 조건 바꿔서 그리드 값 은 바뀌는데 카운트 내용은 그대로니 답답하네요 ㅠㅠ

**Comment by lhslive** [comment]
```
myGrid.setList({
  ajaxUrl:"loadGrid.php",
  ajaxPars:"param1=1¶m2=2", // {String|Object}
  onLoad:function(){
    myGrid.setStatus(myGrid.list.length);
  }
});


```
이런 형태로 해보세요.

**Comment by bloodiel** [comment]
와 잘되네요 두서없이 주저리주저리 써서 일기 어려우셨을텐데 좋은 답변 주셔서 감사합니다.

복받으실 거예요 ^^
