### ISSUE TITLE
AXGrid, 모바일에서 수평 스크롤과 페이징 버튼이 터치로 동작하지 않습니다.

### ISSUE THREAD

**Issue by DevChangil** [thomasJang/axisj#874]
사용하는 Axisj 버전은 1.1.2 입니다. 안드로이드 화면에서 ViewMode가 grid인 AXGrid의 수평 스크롤과 페이징 버튼이 터치로 조작되지 않습니다. Axisj 사이트의 AXGrid 샘플도 마찬가지인 것 같습니다. 버그인가요?

**Comment by thomasJang** [comment]
안드로이드 버전에 따라 다를 것 같습니다. 터치 이벤트에 속성이 다른 경우 터치 스크롤이 오류가 있을 수 있습니다.
최근 버전으로 테스트 해봐주세요.
