### ISSUE TITLE
언제부터인가 Excel 이 안되네요.

### ISSUE THREAD

**Issue by weppl** [thomasJang/axisj#899]
샘플사이트에서도 ( http://dev.axisj.com/samples/AXGrid/index.html ) 
엑셀이 안되네요. 

무슨 이유일까요 ?

**Comment by lhslive** [comment]
페이지 하단에 보시면 추출된 데이터가 뿌려지고 있습니다..
문자로 넘겨서 서버에서 가공해서 활용 하세요
